version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
  groups:
    maven:
      patterns:
        - "*"
  ignore:
  - dependency-name: io.takari.tycho:tycho-support
    versions:
    - "> 0.17.0"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  groups:
    github-actions:
      patterns:
        - "*"
