version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
branches:
  only:
    - main
  except:
    - gh-pages
os: Windows Server 2016
image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile('http://www.us.apache.org/dist/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.zip', 'C:\maven-bin.zip')
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.5.2\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean verify
